/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Model.Bao;
import Model.Sach;
import Model.TapChi;
import Services.QuanLiThuVien;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class AddFrame extends javax.swing.JFrame {
    Bao bao;
    TapChi tapchi;
    Sach sach;
    QuanLiThuVien qltv;
    /**
     * Creates new form AddFrame
     */
    public AddFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        rdbtSach.setSelected(true);
        if(rdbtTapChi.isSelected())
        {
            lbMa.setText("Mã tạp chí:");
            txtMa.setText("TC");
            txt4.setText("");
            lb4.setText("Số phát hành:");
            lb5.setText("Tháng phát hành:");
            txt5.setEnabled(true);
        }
        else if(rdbtSach.isSelected())
        {
            lbMa.setText("Mã sách:");
            txtMa.setText("SA");
            lb4.setText("Tên tác giả:");
            lb5.setText("Số trang");
            txt5.setEnabled(true);
        }
        if(rdbtBao.isSelected())
        {
            lbMa.setText("Mã báo:");
            txtMa.setText("BA");
            lb4.setText("Ngày phát hành: ");
            txt4.setText("dd/mm/yyyy");
            lb5.setText("");
            txt5.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        rdbtSach = new javax.swing.JRadioButton();
        rdbtTapChi = new javax.swing.JRadioButton();
        rdbtBao = new javax.swing.JRadioButton();
        txtMa = new javax.swing.JTextField();
        txtTenNXB = new javax.swing.JTextField();
        txtSoBan = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        btSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM MỚI");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Thể loại:");

        lbMa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMa.setText("Mã sách:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Tên NXB:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Số bản:");

        lb4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lb4.setText("Tên tác giả:");

        lb5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lb5.setText("Số trang:");

        buttonGroup1.add(rdbtSach);
        rdbtSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbtSach.setText("Sách");
        rdbtSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtSachActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtTapChi);
        rdbtTapChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbtTapChi.setText("Tạp Chí");
        rdbtTapChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtTapChiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtBao);
        rdbtBao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbtBao.setText("Báo");
        rdbtBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtBaoActionPerformed(evt);
            }
        });

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        btSubmit.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btSubmit.setText("Thêm");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNXB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdbtSach)
                                .addGap(71, 71, 71)
                                .addComponent(rdbtTapChi)
                                .addGap(75, 75, 75)
                                .addComponent(rdbtBao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtMa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoBan, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdbtSach)
                    .addComponent(rdbtTapChi)
                    .addComponent(rdbtBao))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMa)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb4)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb5)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSubmit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void rdbtTapChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtTapChiActionPerformed
        if(rdbtTapChi.isSelected())
        {
            lbMa.setText("Mã tạp chí:");
            txtMa.setText("TC");
            txt4.setText("");
            lb4.setText("Số phát hành:");
            lb5.setText("Tháng phát hành:");
            txt5.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtTapChiActionPerformed

    private void rdbtSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtSachActionPerformed
        if(rdbtSach.isSelected())
        {
            lbMa.setText("Mã sách:");
            txtMa.setText("SA");
            lb4.setText("Tên tác giả:");
            lb5.setText("Số trang");
            txt5.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtSachActionPerformed

    private void rdbtBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtBaoActionPerformed
        if(rdbtBao.isSelected())
        {
            lbMa.setText("Mã báo:");
            txtMa.setText("BA");
            lb4.setText("Ngày phát hành: ");
            txt4.setText("dd/mm/yyyy");
            lb5.setText("");
            txt5.setEnabled(false);
        }
    }//GEN-LAST:event_rdbtBaoActionPerformed

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        if(rdbtSach.isSelected())
        {
            sach = new Sach();
            sach.setMaSach(txtMa.getText());
            sach.setTenNXB(txtTenNXB.getText());
            sach.setSoBanPhatHanh(Integer.parseInt(txtSoBan.getText()));
            sach.setTenTacGia(txt4.getText());
            sach.setSoTrang(Integer.parseInt(txt5.getText()));
            
            qltv = new QuanLiThuVien();
            qltv.AddBook(sach);
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            
            try {
                new BooksFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        else
        if(rdbtTapChi.isSelected())
        {
            tapchi = new TapChi();
            tapchi.setMaTapChi(txtMa.getText());
            tapchi.setTenNXB(txtTenNXB.getText());
            tapchi.setSoBanPhatHanh(Integer.parseInt(txtSoBan.getText()));
            tapchi.setSoPhatHanh(Integer.parseInt(txtSoBan.getText()));
            tapchi.setThangPhatHanh(Integer.parseInt(txt5.getText()));
            
            qltv = new QuanLiThuVien();
            qltv.AddJournal(tapchi);
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            
            try {
                new JournalFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        else
        if(rdbtBao.isSelected())
        {
            bao = new Bao();
            bao.setMaBao(txtMa.getText());
            bao.setTenNXB(txtTenNXB.getText());
            bao.setSoBanPhatHanh(Integer.parseInt(txtSoBan.getText()));
            bao.setNgayPhatHanh(txt4.getText());
            
            qltv = new QuanLiThuVien();
            qltv.AddMagazines(bao);
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            
            try {
                new MagazinesFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lbMa;
    private javax.swing.JRadioButton rdbtBao;
    private javax.swing.JRadioButton rdbtSach;
    private javax.swing.JRadioButton rdbtTapChi;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSoBan;
    private javax.swing.JTextField txtTenNXB;
    // End of variables declaration//GEN-END:variables
}
